# Generated by Django 3.0.6 on 2020-05-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ip',
            field=models.CharField(default=2, max_length=15, verbose_name='ip клиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='django_movies.Movies', verbose_name='Фильм'),
        ),
    ]
